server.port=9000
spring.application.name=apigateway
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
spring.security.oauth2.resourceserver.jwt.secret-key=dGhpc0lzQVNlY3VyZVRlc3RLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24xMjM0NTY=
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
jwt.secret=dGhpc0lzQVNlY3VyZVRlc3RLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24xMjM0NTY=
internal.secret-key=11217b83-b544-4492-b84c-f7a78221102f
